name: dokitamobile
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  gap: ^3.0.1
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  flutter_native_splash: ^2.4.6
  smooth_page_indicator: ^1.2.1
  get_storage: ^2.1.1
  dio: ^5.8.0+1
  fluttertoast: ^8.2.12
  elegant_notification: ^2.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logos/logo_light.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#1BA39C"
  adaptive_icon_foreground: "assets/logos/logo_foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/brands/
    - assets/illustrations/
